package io.proffitt.coherence.settings;

import java.util.HashMap;

public class Keys {
	private static HashMap<String, Integer>	mapping;
	static {
		mapping = new HashMap<String, Integer>();
		mapping.put("SPACE", new Integer(0x20));
		mapping.put("APOSTROPHE", new Integer(0x27));
		mapping.put("COMMA", new Integer(0x2C));
		mapping.put("MINUS", new Integer(0x2D));
		mapping.put("PERIOD", new Integer(0x2E));
		mapping.put("SLASH", new Integer(0x2F));
		mapping.put("0", new Integer(0x30));
		mapping.put("1", new Integer(0x31));
		mapping.put("2", new Integer(0x32));
		mapping.put("3", new Integer(0x33));
		mapping.put("4", new Integer(0x34));
		mapping.put("5", new Integer(0x35));
		mapping.put("6", new Integer(0x36));
		mapping.put("7", new Integer(0x37));
		mapping.put("8", new Integer(0x38));
		mapping.put("9", new Integer(0x39));
		mapping.put("SEMICOLON", new Integer(0x3B));
		mapping.put("EQUAL", new Integer(0x3D));
		mapping.put("A", new Integer(0x41));
		mapping.put("B", new Integer(0x42));
		mapping.put("C", new Integer(0x43));
		mapping.put("D", new Integer(0x44));
		mapping.put("E", new Integer(0x45));
		mapping.put("F", new Integer(0x46));
		mapping.put("G", new Integer(0x47));
		mapping.put("H", new Integer(0x48));
		mapping.put("I", new Integer(0x49));
		mapping.put("J", new Integer(0x4A));
		mapping.put("K", new Integer(0x4B));
		mapping.put("L", new Integer(0x4C));
		mapping.put("M", new Integer(0x4D));
		mapping.put("N", new Integer(0x4E));
		mapping.put("O", new Integer(0x4F));
		mapping.put("P", new Integer(0x50));
		mapping.put("Q", new Integer(0x51));
		mapping.put("R", new Integer(0x52));
		mapping.put("S", new Integer(0x53));
		mapping.put("T", new Integer(0x54));
		mapping.put("U", new Integer(0x55));
		mapping.put("V", new Integer(0x56));
		mapping.put("W", new Integer(0x57));
		mapping.put("X", new Integer(0x58));
		mapping.put("Y", new Integer(0x59));
		mapping.put("Z", new Integer(0x5A));
		mapping.put("LEFT_BRACKET", new Integer(0x5B));
		mapping.put("BACKSLASH", new Integer(0x5C));
		mapping.put("RIGHT_BRACKET", new Integer(0x5D));
		mapping.put("GRAVE_ACCENT", new Integer(0x60));
		mapping.put("WORLD_1", new Integer(0xA1));
		mapping.put("WORLD_2", new Integer(0xA2));
		mapping.put("ESCAPE", new Integer(0x100));
		mapping.put("ENTER", new Integer(0x101));
		mapping.put("TAB", new Integer(0x102));
		mapping.put("BACKSPACE", new Integer(0x103));
		mapping.put("INSERT", new Integer(0x104));
		mapping.put("DELETE", new Integer(0x105));
		mapping.put("RIGHT", new Integer(0x106));
		mapping.put("LEFT", new Integer(0x107));
		mapping.put("DOWN", new Integer(0x108));
		mapping.put("UP", new Integer(0x109));
		mapping.put("PAGE_UP", new Integer(0x10A));
		mapping.put("PAGE_DOWN", new Integer(0x10B));
		mapping.put("HOME", new Integer(0x10C));
		mapping.put("END", new Integer(0x10D));
		mapping.put("CAPS_LOCK", new Integer(0x118));
		mapping.put("SCROLL_LOCK", new Integer(0x119));
		mapping.put("NUM_LOCK", new Integer(0x11A));
		mapping.put("PRINT_SCREEN", new Integer(0x11B));
		mapping.put("PAUSE", new Integer(0x11C));
		mapping.put("F1", new Integer(0x122));
		mapping.put("F2", new Integer(0x123));
		mapping.put("F3", new Integer(0x124));
		mapping.put("F4", new Integer(0x125));
		mapping.put("F5", new Integer(0x126));
		mapping.put("F6", new Integer(0x127));
		mapping.put("F7", new Integer(0x128));
		mapping.put("F8", new Integer(0x129));
		mapping.put("F9", new Integer(0x12A));
		mapping.put("F10", new Integer(0x12B));
		mapping.put("F11", new Integer(0x12C));
		mapping.put("F12", new Integer(0x12D));
		mapping.put("F13", new Integer(0x12E));
		mapping.put("F14", new Integer(0x12F));
		mapping.put("F15", new Integer(0x130));
		mapping.put("F16", new Integer(0x131));
		mapping.put("F17", new Integer(0x132));
		mapping.put("F18", new Integer(0x133));
		mapping.put("F19", new Integer(0x134));
		mapping.put("F20", new Integer(0x135));
		mapping.put("F21", new Integer(0x136));
		mapping.put("F22", new Integer(0x137));
		mapping.put("F23", new Integer(0x138));
		mapping.put("F24", new Integer(0x139));
		mapping.put("F25", new Integer(0x13A));
		mapping.put("KP_0", new Integer(0x140));
		mapping.put("KP_1", new Integer(0x141));
		mapping.put("KP_2", new Integer(0x142));
		mapping.put("KP_3", new Integer(0x143));
		mapping.put("KP_4", new Integer(0x144));
		mapping.put("KP_5", new Integer(0x145));
		mapping.put("KP_6", new Integer(0x146));
		mapping.put("KP_7", new Integer(0x147));
		mapping.put("KP_8", new Integer(0x148));
		mapping.put("KP_9", new Integer(0x149));
		mapping.put("KP_DECIMAL", new Integer(0x14A));
		mapping.put("KP_DIVIDE", new Integer(0x14B));
		mapping.put("KP_MULTIPLY", new Integer(0x14C));
		mapping.put("KP_SUBTRACT", new Integer(0x14D));
		mapping.put("KP_ADD", new Integer(0x14E));
		mapping.put("KP_ENTER", new Integer(0x14F));
		mapping.put("KP_EQUAL", new Integer(0x150));
		mapping.put("LEFT_SHIFT", new Integer(0x154));
		mapping.put("LEFT_CONTROL", new Integer(0x155));
		mapping.put("LEFT_ALT", new Integer(0x156));
		mapping.put("LEFT_SUPER", new Integer(0x157));
		mapping.put("RIGHT_SHIFT", new Integer(0x158));
		mapping.put("RIGHT_CONTROL", new Integer(0x159));
		mapping.put("RIGHT_ALT", new Integer(0x15A));
		mapping.put("RIGHT_SUPER", new Integer(0x15B));
		mapping.put("MENU", new Integer(0x15C));
	}
	public static int getKey(String name) {
		return mapping.get(name) == null ? -1 : mapping.get(name);
	}
}
